#!/usr/bin/env bash
# =============================================================================
#  evidence.sh — the proof leaves the laptop.
#
#  The receipt is the strongest artefact this kit produces, and it is invisible:
#  .vantry/receipts/ is gitignored, correctly (a stale proof must not travel
#  with the code, and an untracked receipt would change the very digest it
#  certifies). So the durable end of the chain is NOT the receipt file — it is
#  the merged PR that carries the observation, plus this page, generated at
#  release time and committed.
#
#  This is a PURE READER. It writes exactly one file and no state. Sources:
#    git log <since>..HEAD --first-parent   what landed on the trunk
#
#    --merges was wrong: this kit recommends SQUASH merges (one commit per PR on
#    the trunk), and a squash produces an ordinary commit with one parent. So the
#    registry saw nothing and could conclude "no behavioural change" for a release
#    that shipped a month of them. --first-parent counts what actually landed,
#    under either merge policy.
#    the "## Verification evidence" block of each merged PR (gh, when available)
#    .vantry/overrides/*.json         committed, therefore reviewable
#    .vantry/reviews/*.json           committed security / code / design verdicts
#    vantry.yml acceptance:           the criteria still standing guard
#
#  Usage: scripts/evidence.sh [since-ref] [version]
#         scripts/evidence.sh v2.0.1 v2.1.0
# =============================================================================
set -uo pipefail
_here="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=lib/vantry-common.sh
. "$_here/lib/vantry-common.sh"
cd "$VANTRY_ROOT" || exit 1

SINCE="${1:-$(git describe --tags --abbrev=0 2>/dev/null || git rev-list --max-parents=0 HEAD | head -1)}"
VERSION="${2:-$(cat VERSION 2>/dev/null || echo unreleased)}"
OUT="docs/evidence/${VERSION}.md"
mkdir -p docs/evidence

HAVE_GH=0
command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1 && HAVE_GH=1

{
  echo "# Verification evidence — $VERSION"
  echo
  echo "> Generated by \`scripts/evidence.sh\` from git and from the artefacts the gate"
  echo "> produced. Nothing here is written by hand, and nothing here is a claim: each"
  echo "> line points at a commit, a committed review, or a criterion that is still"
  echo "> executed on every verification."
  echo
  echo "- range: \`$SINCE..HEAD\`"
  echo "- generated at: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  [ "$HAVE_GH" = "0" ] && echo "- ⚠ \`gh\` unavailable or unauthenticated — PR bodies could not be read, so the"
  [ "$HAVE_GH" = "0" ] && echo "  *observed* column below is empty. It is left blank rather than filled in from"
  [ "$HAVE_GH" = "0" ] && echo "  the commit message, because a generated document that guesses is worse than one"
  [ "$HAVE_GH" = "0" ] && echo "  that admits a gap."
  echo

  # ---------------------------------------------------------------- what landed
  echo "## What shipped"
  echo
  N=0
  while IFS= read -r line; do
    [ -n "$line" ] || continue
    N=$((N + 1))
    sha="${line%% *}"; subj="${line#* }"
    pr="$(printf '%s' "$subj" | grep -oE '#[0-9]+' | head -1 | tr -d '#')"
    echo "### ${subj}"
    echo
    echo "- merge commit: \`$sha\`"
    if [ -n "$pr" ]; then
      echo "- pull request: #$pr"
      if [ "$HAVE_GH" = "1" ]; then
        body="$(gh pr view "$pr" --json body -q .body 2>/dev/null || true)"
        ev="$(printf '%s' "$body" | awk '/^##[[:space:]]*Verification evidence/{f=1;next} /^##[[:space:]]/{f=0} f' \
              | grep -vE '^[[:space:]]*(<!--|-->)' | sed '/^[[:space:]]*$/d')"
        if [ -n "$ev" ]; then
          echo "- observed:"
          printf '%s\n' "$ev" | sed 's/^/  > /'
        else
          echo "- observed: _the PR carried no evidence block_"
        fi
      fi
    fi
    echo
  done <<EOF
$(git log "$SINCE..HEAD" --first-parent --pretty='%h %s' 2>/dev/null)
EOF
  [ "$N" -eq 0 ] && echo "_No merge commits in this range. On a single-branch history the changes are in the commit log rather than in merges._"
  echo

  # ------------------------------------------------------- the standing guards
  echo "## Acceptance criteria still standing guard"
  echo
  AC=0
  while IFS= read -r ac; do
    [ -n "$ac" ] || continue
    AC=$((AC + 1))
    id="$(printf '%s' "$ac"  | awk -F' \\| ' '{print $1}')"
    req="$(printf '%s' "$ac" | awk -F' \\| ' '{print $2}')"
    st="$(printf '%s' "$ac"  | awk -F' \\| ' '{print $3}')"
    [ "$AC" = "1" ] && { echo "| id | requirement | what it proves |"; echo "|---|---|---|"; }
    echo "| \`$id\` | \`$req\` | $st |"
  done <<EOF
$(vantry_cfg_list acceptance)
EOF
  if [ "$AC" -eq 0 ]; then
    echo "_None declared. Each criterion added to \`acceptance:\` in \`vantry.yml\` keeps executing on"
    echo "every verification forever — a regression on a requirement blocks the push of someone who"
    echo "has never heard of it._"
  else
    echo
    echo "$AC criterion/criteria run on **every** verification, not only in the sprint that added them."
  fi
  echo

  # ------------------------------------------------------------- the judgements
  echo "## Review verdicts"
  echo
  R=0
  for f in .vantry/reviews/*.json; do
    [ -e "$f" ] || continue
    R=$((R + 1))
    [ "$R" = "1" ] && { echo "| branch | kind | verdict | reviewer |"; echo "|---|---|---|---|"; }
    printf '| `%s` | %s | **%s** | %s |\n' \
      "$(basename "$f" | sed 's/\.[a-z]*\.json$//')" \
      "$(vantry_json_get "$(cat "$f")" kind)" \
      "$(vantry_json_get "$(cat "$f")" verdict)" \
      "$(vantry_json_get "$(cat "$f")" reviewer)"
  done
  [ "$R" -eq 0 ] && echo "_No committed review verdicts in this range._"
  echo

  # -------------------------------------------------------------- the overrides
  echo "## Verifications that were overridden"
  echo
  O=0
  for f in .vantry/overrides/*.json; do
    [ -e "$f" ] || continue
    O=$((O + 1))
    echo "### \`$(basename "$f" .json)\`"
    echo
    echo "- who: $(vantry_json_get "$(cat "$f")" who)"
    echo "- when: $(vantry_json_get "$(cat "$f")" at)"
    echo "- head: \`$(vantry_json_get "$(cat "$f")" head)\`"
    echo "- reason, verbatim:"
    echo
    printf '  > %s\n' "$(vantry_json_get "$(cat "$f")" reason)"
    echo
  done
  if [ "$O" -eq 0 ]; then
    echo "**None.** Every behavioural change in this range earned a passing receipt."
  else
    echo "**$O override(s).** Each one is a human decision to ship without the gate's proof."
    echo "They are listed here, in full and unedited, because an override nobody sees is"
    echo "just a disabled gate."
  fi
  echo
  echo "---"
  echo
  echo "_The verification contract for this project is \`vantry.yml\`; the executable"
  echo "definition of \"verified\" is \`scripts/verify.sh\`. Neither is reproduced here —"
  echo "read them at the tag._"
} > "$OUT"

echo "✓ wrote $OUT"
echo "  COMMIT IT. This page is the only part of the proof that outlives the branch."
[ "$HAVE_GH" = "0" ] && echo "  ⚠ generated without gh: the observed column is empty, not guessed."
exit 0
