#!/usr/bin/env bash
# =============================================================================
#  gen-codeowners.sh — generate .github/CODEOWNERS from vantry.yml.
#
#  One definition of "sensitive", three consumers: the CI security job, the
#  agent-side gate, and human review. v1 had the concept in prose only, so
#  nothing could route a review at all.
#
#  Usage: scripts/gen-codeowners.sh @owner [@owner ...]
# =============================================================================
set -uo pipefail
_here="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=lib/vantry-common.sh
. "$_here/lib/vantry-common.sh"

[ -f "$VANTRY_CFG" ] || { echo "✗ vantry.yml not found."; exit 1; }
[ $# -ge 1 ] || { echo "usage: scripts/gen-codeowners.sh @owner [@owner ...]"; exit 1; }
OWNERS="$*"

OUT="$VANTRY_ROOT/.github/CODEOWNERS"
mkdir -p "$(dirname "$OUT")"

{
  echo "# GENERATED by scripts/gen-codeowners.sh from vantry.yml: sensitive_paths"
  echo "# Edit vantry.yml, then re-run. Hand edits are lost."
  echo "# Requires 'Require review from Code Owners' in branch protection to bite."
  echo
  vantry_cfg_list sensitive_paths | while IFS= read -r g; do
    [ -n "$g" ] || continue
    # CODEOWNERS uses gitignore-style patterns, so most globs pass straight through.
    case "$g" in
      /*) printf '%s %s\n' "$g" "$OWNERS" ;;
      *)  printf '%s %s\n' "$g" "$OWNERS" ;;
    esac
  done
} > "$OUT"

echo "✓ wrote $OUT"
sed -n '4,$p' "$OUT" | sed 's/^/    /'
echo
echo "Next: enable branch protection so it is enforced —"
if [ -f "docs/engineering/branch-protection.md" ]; then
  echo "  see docs/engineering/branch-protection.md"
else
  # That path was printed unconditionally and the installer never writes it, so
  # the instruction dead-ended for every adopter. Say the actual steps.
  echo "  GitHub → Settings → Branches → add a rule for your trunk, and require:"
  echo "    • Require a pull request before merging  (+ require review from Code Owners)"
  echo "    • Require status checks to pass: 'contract is valid', 're-run the verification',"
  echo "      'PR states its evidence', 'sensitive paths need a security review'"
  echo "    • Do not allow bypassing the above settings"
  echo "  Without this, CODEOWNERS is advisory and the security gate can be merged past."
fi
