#!/usr/bin/env bash
# ============================================================================
#  sync-adapters.sh — regenerate every tool adapter from the SINGLE source
#  (AGENTS.md + agents/ + skills/). Edit those; never hand-edit the adapters.
#  bash 3.2 / macOS compatible.
#
#  NON-DESTRUCTIVE GUARANTEES (v1.0.1):
#    - CLAUDE.md / GEMINI.md / copilot-instructions.md are written ONLY between
#      <!-- vantry:adapter:start --> and <!-- vantry:adapter:end -->. A file you
#      or /bootstrap authored keeps everything outside that block.
#    - The .claude/ mirror is never `rm -rf`'d. A file in the mirror with no
#      source is a project-local addition (or a leftover) — the sync REFUSES
#      and names it, rather than deleting your work. Use --force to delete.
#
#  USAGE
#    ./scripts/sync-adapters.sh            # sync (refuses on orphans)
#    ./scripts/sync-adapters.sh --force    # sync AND delete orphaned mirror files
# ============================================================================
set -uo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"; cd "$ROOT" || { echo "✗ cannot enter $ROOT"; exit 1; }
[ -f AGENTS.md ] || { echo "✗ AGENTS.md not found at repo root."; exit 1; }

FORCE=0
CHECK=0
for a in "$@"; do
  case "$a" in
    --force) FORCE=1 ;;
    --check) CHECK=1 ;;
    *) echo "✗ unknown option: $a"; echo "  usage: ./scripts/sync-adapters.sh [--force|--check]"; exit 1 ;;
  esac
done

# --check: run the sync on a throwaway copy and diff. Nothing here is written.
# This is what CI calls, so "I forgot to sync" becomes a red build instead of a
# mirror that quietly drifts for three weeks.
if [ "$CHECK" = "1" ]; then
  T="$(mktemp -d)"; trap 'rm -rf "$T"' EXIT
  # Copy what is ON DISK, not what git tracks: a brand-new skill is untracked
  # until it is committed, and a drift check that cannot see it would report
  # the mirror as stale for exactly as long as the work is in progress.
  for d in agents skills .claude/agents .claude/skills .cursor .windsurf .github; do
    [ -e "$ROOT/$d" ] || continue
    ( cd "$ROOT" && find "$d" -type f 2>/dev/null | while IFS= read -r f; do
        mkdir -p "$T/$(dirname "$f")"; cp "$f" "$T/$f"
      done )
  done
  for f in AGENTS.md CLAUDE.md GEMINI.md; do
    [ -f "$ROOT/$f" ] && cp "$ROOT/$f" "$T/$f"
  done
  mkdir -p "$T/scripts"
  cp "$ROOT/scripts/sync-adapters.sh" "$T/scripts/sync-adapters.sh" 2>/dev/null
  chmod +x "$T/scripts/sync-adapters.sh"
  if ! ( cd "$T" && ./scripts/sync-adapters.sh --force ) >/dev/null 2>&1; then
    echo "✗ sync would fail on this tree"; exit 1
  fi
  DRIFT=0
  for p in .claude/agents .claude/skills CLAUDE.md GEMINI.md .github/copilot-instructions.md \
           .cursor/rules/agent-native.mdc .windsurf/rules/agent-native.md; do
    if ! diff -rq "$ROOT/$p" "$T/$p" >/dev/null 2>&1; then
      echo "✗ out of sync: $p"; DRIFT=1
    fi
  done
  # --check runs in a temp copy and diffs a fixed list of paths. README.md is not
  # generated into that copy, so the version pin has to be checked here — the
  # first version of this check sat at the bottom of the file, which --check
  # never reaches. Dead code in the drift detector is how a pin drifts.
  if [ -f "$ROOT/VERSION" ] && grep -qE 'branch v[0-9]+\.[0-9]+\.[0-9]+' "$ROOT/README.md" 2>/dev/null; then
    V="$(tr -d '[:space:]' < "$ROOT/VERSION")"
    grep -qE "branch v${V}([[:space:]]|$)" "$ROOT/README.md" || {
      echo "✗ out of sync: README.md pins a version that is not v$V"; DRIFT=1; }
  fi
  if [ "$DRIFT" -eq 0 ]; then echo "✓ adapters and mirror are in sync"; else
    echo "  Run ./scripts/sync-adapters.sh and commit the result."; fi
  exit "$DRIFT"
fi

STAMP="$(date +%Y%m%d-%H%M%S)"
BEGIN="<!-- vantry:adapter:start — generated by scripts/sync-adapters.sh. Edit AGENTS.md, not this block. -->"
END="<!-- vantry:adapter:end -->"
RC=0

# ---------------------------------------------------------------------------
# 1) Mirror the portable content into Claude Code's native location.
#    Never `rm -rf`: that deletes any agent or skill the project added itself.
# ---------------------------------------------------------------------------
sync_mirror() {  # $1 = "agents" | "skills"
  local name="$1" src="$ROOT/$1" dst="$ROOT/.claude/$1" f rel orphans=0
  [ -d "$src" ] || return 0
  mkdir -p "$dst"

  if [ -d "$dst" ]; then
    while IFS= read -r f; do
      rel="${f#$dst/}"
      if [ ! -e "$src/$rel" ]; then
        [ "$orphans" -eq 0 ] && echo "✗ .claude/$name holds file(s) with no source in $name/:"
        orphans=$((orphans+1)); echo "      .claude/$name/$rel"
      fi
    done < <(find "$dst" -type f 2>/dev/null)
  fi

  if [ "$orphans" -gt 0 ] && [ "$FORCE" != "1" ]; then
    echo "  These are project-local additions, or leftovers from a source file you deleted."
    echo "  Move them into $name/ (recommended — that is the portable location),"
    echo "  or re-run with --force to delete them from the mirror."
    return 1
  fi
  if [ "$orphans" -gt 0 ]; then
    while IFS= read -r f; do
      rel="${f#$dst/}"; [ -e "$src/$rel" ] || rm -f "$f"
    done < <(find "$dst" -type f 2>/dev/null)
    # A skill directory with no SKILL.md left in it is worse than no directory.
    find "$dst" -mindepth 1 -type d -empty -delete 2>/dev/null
    echo "  ⚠ --force: deleted $orphans orphaned file(s) from .claude/$name"
  fi

  while IFS= read -r f; do
    rel="${f#$src/}"
    mkdir -p "$(dirname "$dst/$rel")"
    cp "$f" "$dst/$rel" || return 1
  done < <(find "$src" -type f 2>/dev/null)
  echo "  ✓ mirrored $name/ → .claude/$name/"
}

mkdir -p .claude
sync_mirror agents || RC=1
sync_mirror skills || RC=1

# ---------------------------------------------------------------------------
# 2) Adapters. Markered write for the files a project legitimately authors.
# ---------------------------------------------------------------------------
write_marked() {  # $1 = path; body on stdin
  local path="$1" body lines s e
  body="$(mktemp)"; cat > "$body"

  if [ ! -e "$path" ]; then
    { printf '%s\n' "$BEGIN"; cat "$body"; printf '%s\n' "$END"; } > "$path"
    echo "  + $path (created)"; rm -f "$body"; return 0
  fi

  if grep -qF "$BEGIN" "$path" && grep -qF "$END" "$path"; then
    s="$(grep -nF "$BEGIN" "$path" | head -1 | cut -d: -f1)"
    e="$(grep -nF "$END"   "$path" | head -1 | cut -d: -f1)"
    if [ -n "$s" ] && [ -n "$e" ] && [ "$e" -gt "$s" ]; then
      # `sed -n "1,0p"` prints line 1 on both BSD and GNU sed — which would
      # re-emit the opening marker and duplicate the block. Guard on s > 1.
      { [ "$s" -gt 1 ] && sed -n "1,$((s-1))p" "$path"
        printf '%s\n' "$BEGIN"; cat "$body"; printf '%s\n' "$END"
        sed -n "$((e+1)),\$p" "$path"
      } > "$path.vantry-tmp" && mv "$path.vantry-tmp" "$path"
      echo "  ✓ $path (block updated, your content untouched)"; rm -f "$body"; return 0
    fi
  fi

  # No markers. A short file that already points at AGENTS.md is a legacy stub
  # this script itself wrote — safe to replace. Anything else is YOUR file.
  lines="$(wc -l < "$path" | tr -d ' ')"
  if [ "${lines:-0}" -le 12 ] && grep -q "AGENTS.md" "$path"; then
    { printf '%s\n' "$BEGIN"; cat "$body"; printf '%s\n' "$END"; } > "$path"
    echo "  ✓ $path (legacy stub upgraded to a markered block)"
  else
    cp "$path" "$path.vantry-bak-$STAMP"
    { printf '%s\n' "$BEGIN"; cat "$body"; printf '%s\n' "$END"; printf '\n'
      cat "$path.vantry-bak-$STAMP"
    } > "$path"
    echo "  ~ $path had no vantry markers — backed up to $(basename "$path").vantry-bak-$STAMP;"
    echo "    the generated block was PREPENDED and your content kept below it."
  fi
  rm -f "$body"
}

write_plain() {  # $1 = path; body on stdin. For vantry-owned rule files with frontmatter.
  local path="$1" body
  body="$(mktemp)"; cat > "$body"
  mkdir -p "$(dirname "$path")"
  if [ -e "$path" ] && ! cmp -s "$body" "$path"; then
    cp "$path" "$path.vantry-bak-$STAMP"
    echo "  ~ backed up $path → $(basename "$path").vantry-bak-$STAMP"
  fi
  cp "$body" "$path" && echo "  ✓ $path"
  rm -f "$body"
}

# The bare @AGENTS.md below is an IMPORT, not decoration, and it must stay on
# its own line outside any code span. Claude Code reads CLAUDE.md — not
# AGENTS.md — so with a markdown link here the binding working agreement was
# merely *referenced* and never entered the session context. On the one tool the
# capability matrix calls "the fullest experience", the agreement was the one
# thing not loaded.
write_marked CLAUDE.md <<'EOF'
# CLAUDE.md — Claude Code

@AGENTS.md

## Claude Code specifics
The import above IS the binding working agreement — read it as law, not as a pointer.
The roles are native sub-agents in `.claude/agents/` and the playbooks are auto-invoked skills in
`.claude/skills/`, both generated from the portable `agents/` + `skills/`. When in doubt, AGENTS.md wins.

**The gate runs here, not just at push.** A Stop hook refuses to end a turn on an unverified behavioural
change, and `.claude/hooks/bash-guard.sh` denies forging a receipt, disabling the hooks, or committing
unverified work. Run `scripts/verify.sh --status` whenever you are unsure where a branch stands.
EOF

write_marked GEMINI.md <<'EOF'
# GEMINI.md — Gemini CLI
This project uses the **agent-native method**. The binding working agreement is in **AGENTS.md** (repo root) — read it first.
Adopt the fitting role from `agents/`, follow the matching playbook in `skills/`, and honor the security-first /
verification-first principles + conventions described there.
EOF

mkdir -p .github
write_marked .github/copilot-instructions.md <<'EOF'
# Copilot instructions
This repository follows the **agent-native method**. Read **AGENTS.md** (repo root) — the binding working agreement.
Adopt the fitting role from `agents/`; follow the matching playbook in `skills/`; security-first (server-side authz,
row-security + allow/deny tests); verification-first (ship the test); one concern per PR; Conventional Commits;
never leak secrets or raw errors. Full detail + the lifecycle + conventions live in AGENTS.md.
EOF

write_plain .cursor/rules/agent-native.mdc <<'EOF'
---
description: The agent-native working agreement — specialist roles + verification-first playbooks + delivery loop.
alwaysApply: true
---
This project uses the agent-native method. The full, binding working agreement is in AGENTS.md at the repo root.
Adopt the specialist role in `agents/` that fits the task; follow the matching playbook in `skills/`.
Security-first, verification-first, one concern per change, tests prove behavior (allow AND deny for authz). See AGENTS.md.
EOF

write_plain .windsurf/rules/agent-native.md <<'EOF'
---
trigger: always_on
---
This project uses the agent-native method — the binding working agreement is AGENTS.md at the repo root.
Adopt the specialist role in `agents/` that fits the task; follow the matching playbook in `skills/`.
Security-first, verification-first, one concern per change, tests prove behavior (allow AND deny for authz). See AGENTS.md.
EOF

echo
if [ "$RC" -eq 0 ]; then
  echo "✓ Synced from AGENTS.md → CLAUDE.md · GEMINI.md · .cursor/rules · .github/copilot-instructions.md · .windsurf/rules"
  echo "✓ Mirrored agents/ + skills/ → .claude/ (Claude Code auto-discovery)"
else
  echo "✗ Sync INCOMPLETE — the mirror was left alone where it holds files with no source (see above)."
fi

# ---------------------------------------------------------- README version pin
# The quickstart pinned v3.1.0 while VERSION said 3.8.1, so anyone following the
# greenfield quickstart literally cloned a kit seven versions old — one whose
# /bootstrap produces a backlog its own linter rejects. A number a human has to
# remember to bump is a number that drifts; derive it.
if [ -f "$ROOT/VERSION" ] && [ -f "$ROOT/README.md" ]; then
  V="$(tr -d '[:space:]' < "$ROOT/VERSION")"
  if grep -qE 'branch v[0-9]+\.[0-9]+\.[0-9]+' "$ROOT/README.md"; then
    if [ "${1:-}" = "--check" ]; then
      grep -qE "branch v${V}( |$)" "$ROOT/README.md" || {
        echo "✗ README.md pins a version that is not $V — run ./scripts/sync-adapters.sh" >&2; exit 1; }
    else
      sed -i.vantry-bak -E "s#branch v[0-9]+\.[0-9]+\.[0-9]+#branch v${V}#g" "$ROOT/README.md"
      rm -f "$ROOT/README.md.vantry-bak"
    fi
  fi
fi

exit "$RC"
